### ISSUE TITLE
New version won't compile

### ISSUE THREAD

**Issue by thosvarley** [Abzinger/SxPID#5]
If I follow the install instructions, the pip command errors out with:

`Building wheel for ecos (setup.py) ... error`
`ERROR: Command errored out with exit status 1:`
...Then lots of crap from GCC...
`compilation terminated.`
 `error: command 'gcc' failed with exit status 1`
 `----------------------------------------`
 `ERROR: Failed building wheel for ecos`

The issues seems to be with the ecos build.

**Comment by Abzinger** [comment]
Sorry for the bug.  Ecos package is not needed for SxPID, therefore, I just removed it from the requirements. I should admit that I need to clean the requirements file.
In case there are other issues, a quick fix is to use SxPID is 

1. clone the repository 
2. create a symbolic link (shortcut for windows users) to your working directory
3. import SxPID should work

Cheers

**Comment by thosvarley** [comment]
It works, thanks!
